version: '3.5'

x-pihole-mount:
  &pihole-mount
  type: bind
  source: /var/rpi/pihole/etc/pihole
  target: /etc/pihole
x-dnsmasq-mount:
  &dnsmasq-mount
  type: bind
  source: /var/rpi/pihole/etc/dnsmasq.d
  target: /etc/dnsmasq.d

services:
  pihole:
    image: "pihole/pihole:v4.0_armhf"
    networks:
      - outside
    # If using host networking, all exposed ports are already visible
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "80:80/tcp"
    #  - "443:443/tcp"
    volumes:
      - *pihole-mount
      - *dnsmasq-mount
      #alternative if not using filesystem mounts
      #will also need to uncomment "volumes" below and remove extensions
      - pihole_data:
      - dnsmasq_data:
      
    environment:
      ServerIP: 192.168.2.2
      DNS1: 185.228.168.168
      DNS2: 185.228.169.168
      # jwilder/proxy envs, see readme for more info
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.local
      VIRTUAL_PORT: 80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  outside:
    external:
      name: "host"
# Use instead of filesystem mounts
#volumes:
#  pihole_data:
#  dnsmasq_data:
  

